services:
  - name: new-discord-bot
    type: web
    env: docker
    plan: free
    branch: main
    root: new-discord-bot
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        sync: false
    healthCheckPath: /healthz
