services:
  - name: new-discord-bot
    type: web
    env: node
    plan: free
    branch: main
    buildCommand: cd new-discord-bot && npm install && npm run build
    startCommand: cd new-discord-bot && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        sync: false
    healthCheckPath: /healthz
