services:
  - name: new-discord-bot
    type: web
    env: node
    plan: free
    branch: main
    rootDir: new-discord-bot
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        sync: false
    healthCheckPath: /healthz
